name: netflix API CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: Netflix.settings
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Requiments
        run: pip install -r requiements.txt
      - name: Run Tests
        run: pytest
